; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32s3
build_dir = .wb_build

[env]
platform = espressif32@^6.0.0
framework = arduino
monitor_speed = 115200
upload_speed = 921600

[env:esp32s3]
board = esp32-s3-devkitc-1
board_build.flash_size = 16MB
board_build.flash_mode = dio
board_build.partitions = partitions_16MB.csv
board_build.arduino.memory_type = qio_opi
upload_port = COM7
monitor_port = COM7
monitor_filters = esp32_exception_decoder, time
lib_extra_dirs = 
	${PROJECT_DIR}/../4.0inch_ESP32-4848S040/1-Demo/Demo_Arduino/Libraries
lib_ignore = 
	Time
build_flags = 
	-DBOARD_HAS_PSRAM
	-DCONFIG_SPIRAM_USE_MALLOC=1
	-DCONFIG_SPIRAM_TRY_ALLOCATE_WIFI_LWIP=1
	-DF_CPU=240000000L
	-DCORE_DEBUG_LEVEL=1
	-DLV_COLOR_16_SWAP=0
	-DLV_LVGL_H_INCLUDE_SIMPLE
	-D_GNU_SOURCE
lib_deps = 
	adafruit/Adafruit BusIO@^1.11.0
	tamctec/TAMC_GT911@^1.0.2
