[platformio]
default_envs = esp32s3

[env:esp32s3]
platform = espressif32@^6.0.0
board = esp32-s3-devkitc-1
board_build.flash_size = 16MB
board_build.flash_mode = dio
board_build.arduino.memory_type = qio_opi
framework = arduino
monitor_speed = 115200
upload_port = COM7
upload_speed = 921600
lib_extra_dirs = 
	${PROJECT_DIR}/../../4.0inch_ESP32-4848S040/1-Demo/Demo_Arduino/Libraries
lib_ignore = 
	Time
build_flags =
	-DBOARD_HAS_PSRAM
	-DCORE_DEBUG_LEVEL=1
	-DLV_COLOR_16_SWAP=0
